databases:
  - name: mysite
    databaseName: mysite
    user: mysite
    plan: free

services:
  - type: web
    name: my-rails-app
    env: ruby
    buildCommand: bundle install && bundle exec rails db:migrate
    startCommand: bundle exec rails server -b 0.0.0.0

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default